### ISSUE TITLE
Todo-Tracker

### ISSUE THREAD

**Issue by Zabuzard** [Zabuzard/Discord-Plays#1]
* [x] poc
* [x] basic setup
* [x] discordkt stuff
* [x] coffeebg stuff
* [x] wire up input
* [x] wire up image
* [x] gif rendering
* [x] mute sound
* [x] proper code architecture
* [x] permission checks on all commands
* [x] setup commands
* [x] admin commands
* [x] option to lock input for non-owners
* [x] proper startup and shutdown
* [x] config
* [x] limit input per-user to 2 seconds or so (prevent spamming)
* [x] overlay showing the input queues
* [x] overlay should be rendered so that its exposed to jframe as well
* [x] only one stream per guild (or channel?)
* [x] option for owner to send a message banner in the image
* [x] option for host to send a message in the control-embed
* [x] add or remove owners via user-selection command
* [x] local display
* [x] retry on exception
* [x] speed up gif, build it per-frame instead of all at once
* [x] owner ban input from a specific user
* [x] ~~individual listeners for `acceptFrame/acceptGif` have to be executed async to not block each other~~
* [x] proper offline image if `/stream` while currently offline - instead of _"will start soon"_
* [x] rediscover messages after restart
* [x] re-wire buttons after restart
* [x] send proper offline image on shutdown
* [x] save-game reminder
* [x] save-game routine
* [x] change overlay-buttons with pics
* [x] reverse overlay order (new inputs at bottom)
* [x] pause emulation if no input for 5min
* [x] persist stats
* [x] tracking of unpaused time
* [x] dump the images somewhere so that one can create a playthrough video at the end
* [x] logging
* [x] command to change log level
* [x] add date/time to overlay
* [x] global chat messages
* [x] pin messages (first and global messages)
* [x] video command
* [x] autolock input to owners on startup
* [x] global banner message whenever input is locked
* [x] chat in overlay
* [x] cross-community chat features
* [x] check user rgb inverted
* [x] uptime duration formatting
* [x] readme doc
* [x] jar
* [x] release first version

```java
ffmpeg -framerate 20 -r 20 -i "2023-02-23/%d frame.png" -pix_fmt yuv420p -profile:v high -level:v 4.1 -crf:v 20 -movflags +faststart output.mp4
```
